### PR TITLE
fix: key prefix support int transactions (Put and GetOpt)

### LINKED ISSUE #1017: isPrefix in GetOp don't work
**Describe the bug**
jetcd version 0.5.10
I tryed to get range values by prefix in txn. But I can't get any value by using isPrex(). When I replace "isPrefix()" by "withPrefix()", it works.

**To Reproduce**
```
void test() throws ExecutionException, InterruptedException {
        Client client = Client.builder().endpoints("http://localhost:2379").build();
        Lease lease = client.getLeaseClient();
        String lockName = "/myLock";

        Long leaseId = lease.grant(10).get().getID();

        KV kvClient = client.getKVClient();
        String lockKey = lockName + "/" + "owner";
        Cmp cmp = new Cmp(ByteSequence.from(lockKey.getBytes()), Cmp.Op.EQUAL, CmpTarget.createRevision(0));
        Op.PutOp putOp = Op.put(ByteSequence.from(lockKey.getBytes()), ByteSequence.from("0".getBytes()), PutOption.newBuilder().withLeaseId(leaseId).build());
        Op.GetOp getOwner = Op.get(ByteSequence.from(lockName, Charset.defaultCharset()), GetOption.newBuilder().isPrefix(true).build());

        TxnResponse response = kvClient.txn().If(cmp).Then(putOp, getOwner).Else(getOwner).commit().get();

        for (PutResponse putResponse : response.getPutResponses()) {
            log.info("transaction putResponse {}", putResponse);
        }

        for (GetResponse getResponse : response.getGetResponses()) {
            log.info("transaction getResponse {}", getResponse);
        }

        GetResponse getResponse = kvClient.get(ByteSequence.from(lockName, Charset.defaultCharset()), GetOption.newBuilder().isPrefix(true).build()).get();
        log.info("getResponse {}", getResponse);
    }
```

In the response there is nothing printed. But In getResponse the value is printed.

And when I replace isPrefix by withPrefix, it works.
```
void test2() throws ExecutionException, InterruptedException {
        Client client = Client.builder().endpoints("http://localhost:2379").build();
        Lease lease = client.getLeaseClient();
        String lockName = "/myLock";

        Long leaseId = lease.grant(10).get().getID();

        KV kvClient = client.getKVClient();
        String lockKey = lockName + "/" + "owner";
        Cmp cmp = new Cmp(ByteSequence.from(lockKey.getBytes()), Cmp.Op.EQUAL, CmpTarget.createRevision(0));
        Op.PutOp putOp = Op.put(ByteSequence.from(lockKey.getBytes()), ByteSequence.from("0".getBytes()), PutOption.newBuilder().withLeaseId(leaseId).build());
        Op.GetOp getOwner = Op.get(ByteSequence.from(lockName, Charset.defaultCharset()), GetOption.newBuilder().withPrefix(ByteSequence.from(lockName, Charset.defaultCharset())).build());

        TxnResponse response = kvClient.txn().If(cmp).Then(putOp, getOwner).Else(getOwner).commit().get();

        for (PutResponse putResponse : response.getPutResponses()) {
            log.info("transaction putResponse {}", putResponse);
        }

        for (GetResponse getResponse : response.getGetResponses()) {
            log.info("transaction getResponse {}", getResponse);
        }

        GetResponse getResponse = kvClient.get(ByteSequence.from(lockName, Charset.defaultCharset()), GetOption.newBuilder().isPrefix(true).build()).get();
        log.info("getResponse {}", getResponse);
    }
```
        

**Expected behavior**
isPrefix works as it works in get method

**Additional context**
I found this in get method in KVImpl.java 
https://github.com/etcd-io/jetcd/blob/release-0.5.10/jetcd-core/src/main/java/io/etcd/jetcd/KVImpl.java#L110
```
       if (!option.getEndKey().isPresent() && option.isPrefix()) {
            ByteSequence endKey = OptionsUtil.prefixEndOf(key);
            builder.setRangeEnd(Util.prefixNamespaceToRangeEnd(endKey.getByteString(), namespace));
        }
```
But same code in GetOp class in Op.java is not existed.
https://github.com/etcd-io/jetcd/blob/release-0.5.10/jetcd-core/src/main/java/io/etcd/jetcd/op/Op.java#L108

### PR DESCRIPTION
**Pull request by sudoHackIn**
Because grpc request mapping is the same for KV and Transactions, it's better for me to reuse it.
So the simplest solution was - additional static util class with this logic.

After of package changing,  [ByteSequence.toByteString](https://github.com/etcd-io/jetcd/blob/0537b7fe62f8985d2a0de554d52d2c05ec90789a/jetcd-core/src/main/java/io/etcd/jetcd/ByteSequence.java#L117) is not longer possible. So, i have additional conversion's, which i don't like. 

Fixes #1017

### CODE REVIEW

File: jetcd-core/src/main/java/io/etcd/jetcd/op/Op.java [hunk 1]
```diff
@@ -29,8 +25,7 @@
 
 import com.google.protobuf.ByteString;
 
-import static io.etcd.jetcd.options.OptionsUtil.toRangeRequestSortOrder;
-import static io.etcd.jetcd.options.OptionsUtil.toRangeRequestSortTarget;
+import static io.etcd.jetcd.support.ProtoRequestMapper.*;
```
Comment (lburgazzoli) [inline jetcd-core/src/main/java/io/etcd/jetcd/op/Op.java:28]: please don't use wildcard import as it does not make it clear what is being imported

File: jetcd-core/src/main/java/io/etcd/jetcd/support/ProtoRequestMapper.java [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+import io.etcd.jetcd.options.GetOption;
+import io.etcd.jetcd.options.OptionsUtil;
+import io.etcd.jetcd.options.PutOption;
+
+import com.google.protobuf.ByteString;
+
+import static io.etcd.jetcd.options.OptionsUtil.toRangeRequestSortOrder;
+import static io.etcd.jetcd.options.OptionsUtil.toRangeRequestSortTarget;
+
+public class ProtoRequestMapper {
```
Comment (lburgazzoli) [inline jetcd-core/src/main/java/io/etcd/jetcd/support/ProtoRequestMapper.java:21]: this can be made final

Comment (lburgazzoli) [reply jetcd-core/src/main/java/io/etcd/jetcd/support/ProtoRequestMapper.java:21]: Also, it can be moved to the same package as the `Util` class

**Review by lburgazzoli — CHANGES_REQUESTED** [review]
Some small things to be fixed and some tests are failing

File: jetcd-core/src/main/java/io/etcd/jetcd/op/Op.java (hunk 1 above)
Comment (sudoHackIn) [reply jetcd-core/src/main/java/io/etcd/jetcd/op/Op.java:28]: ok, i see

File: jetcd-core/src/main/java/io/etcd/jetcd/support/ProtoRequestMapper.java (hunk 2 above)
Comment (sudoHackIn) [reply jetcd-core/src/main/java/io/etcd/jetcd/support/ProtoRequestMapper.java:21]: the main one - io.etcd.jetcd? Ok, it'll help with additional boxing and  ByteSequence.toByteString (that is package private)

Comment (lburgazzoli) [reply jetcd-core/src/main/java/io/etcd/jetcd/support/ProtoRequestMapper.java:21]: yes, we may think to have better api vs impl separation in the future like when we can use sealed classes/interfaces

**Comment by sudoHackIn** [comment]
> Some small things to be fixed and some tests are failing

fixed

**Comment by sudoHackIn** [comment]
How do you think, do we still need support java 1.8 java as sometimes requested? If yes, i can try to implement support for this

**Comment by lburgazzoli** [comment]
> How do you think, do we still need java 1.8 java support, as sometimes requested? If yes, i can try to implement support for java, 1.8

if you have time, that would be ok however I'd really like to drop Java 1.8

**Review by lburgazzoli — APPROVED** [review]
